### PR TITLE
compute: fix bug in import function

### LINKED ISSUE #22: terraform import exoscale_compute fails
I am trying to import an existing compute instance that has been created with terraform before but the state has been lost.

<details>
<summary>The resources of the compute, ip and secondary up looks like this</summary>

``` tf
resource "exoscale_ipaddress" "xxx-production" {
  zone                     = "${local.primary_zone}"
  healthcheck_mode         = "http"
  healthcheck_port         = 80
  healthcheck_path         = "/status"
  healthcheck_interval     = 15
  healthcheck_timeout      = 5
  healthcheck_strikes_ok   = 2
  healthcheck_strikes_fail = 4

  lifecycle {
    prevent_destroy = true
  }
}

resource "exoscale_secondary_ipaddress" "xxx-production01" {
  compute_id = "${exoscale_compute.xxx-web-production01.id}"
  ip_address = "${exoscale_ipaddress.xxx-production.ip_address}"
}

resource "exoscale_compute" "xxx-web-production01" {
  zone         = "${local.primary_zone}"
  display_name = "xxx-web-production01"
  template_id  = "${data.exoscale_compute_template.ubuntu.id}"

  size      = "Micro"
  disk_size = 10
  key_pair  = "${local.ssh_key_pair_name}"
  state     = "Running"

  affinity_group_ids = ["${exoscale_affinity.xxx-web-production.id}"]
  security_group_ids = ["${exoscale_security_group.xxx-web.id}"]

  ip6      = false
  keyboard = "de-ch"

  tags = {
    production = "true"
  }

  timeouts {
    create = "60m"
    delete = "2h"
  }
}
```
</details>

---

I tried it with the ID of the instance (some data is redacted) like it is described in [the blog post](https://www.exoscale.com/syslog/managing-your-existing-infrastructure-with-terraform/#importing-a-compute-instance)
```
$ terraform import exoscale_compute.xxx-web-production01 xxxxxxxx-db9f-4b2f-b70b-f8defb649411
exoscale_compute.xxx-web-production01: Importing from ID "xxxxxxxx-db9f-4b2f-b70b-f8defb649411"...

Error: compute_id: '' expected type 'string', got unconvertible type 'egoscale.UUID'
```

By looking at the code it looks like it is related to the secondary ip of the compute instance
https://github.com/terraform-providers/terraform-provider-exoscale/blob/ef99805cf7bcb348d56e052c1cf652a8cbaa30bb/exoscale/resource_exoscale_compute.go#L847

---

Using the name instead of the id seems to work better but fails too.
```
$ terraform import exoscale_compute.xxx-web-production01 xxx-web-production01
exoscale_compute.xxx-web-production01: Importing from ID "xxx-web-production01"...
exoscale_compute.xxx-web-production01: Import prepared!
  Prepared exoscale_compute for import
  Prepared exoscale_secondary_ipaddress for import
exoscale_secondary_ipaddress.xxx-web-production01: Refreshing state... [id=xxxxxxxx-cc96-4998-b67b-d1591a351fc6_159.100.xx.xx]
exoscale_compute.xxx-web-production01: Refreshing state... [id=xxx-web-production01]

Error: uuid: incorrect UUID length: xxx-web-production01
```

### PR DESCRIPTION
**Pull request by falzm**
This change fixes a bug preventing importing of  `exoscale_compute`
resources with secondary IP addresses attached.

Fixes #22.

### CODE REVIEW

File: exoscale/resource_exoscale_compute.go [hunk 1]
```diff
@@ -844,7 +846,7 @@ func resourceComputeImport(d *schema.ResourceData, meta interface{}) ([]*schema.
 		resource := resourceSecondaryIPAddress()
 		d := resource.Data(nil)
 		d.SetType("exoscale_secondary_ipaddress")
-		if err := d.Set("compute_id", id); err != nil {
+		if err := d.Set("compute_id", id.String()); err != nil {
```
Comment (pierre-emmanuelJ) [inline exoscale/resource_exoscale_compute.go:852]: 👍

**Review by pierre-emmanuelJ — APPROVED** [review]

**Review by illi-j — APPROVED** [review]
