### PR TITLE
fix(iam_role): document editable default and add RequiresReplace

### LINKED ISSUE #505: [Bug]:  default value of editable of exoscale_iam_role
### Current Behavior

The documentation do not tell what is the default value of `editable` of the resource `exoscale_iam_role` : 

> [editable](https://registry.terraform.io/providers/exoscale/exoscale/latest/docs/resources/iam_role#editable-1) (Boolean) Defines if IAM Role Policy is editable or not.

### Expected Behavior

the documentation should tell if it is `true` or `false`

### Steps To Reproduce

_No response_

### Provider Version

0.68

### Terraform Version

N/A

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by natalie-o-perret**
Fixes #505.

## Problem

The `editable` attribute on `exoscale_iam_role` defaults to `true` per the API spec, and cannot be changed after creation (absent from the update endpoint). Neither of these facts were documented, and there was no plan modifier to enforce immutability.

## Changes

- Update description to state the default and that it cannot be changed after creation
- Add `boolplanmodifier.RequiresReplace()` so Terraform plans a destroy+recreate if `editable` changes
- Remove dead update logic that tried to set `editable` on update (the API ignores it)
- Regenerate docs

### Integration Tests
```
$ TF_ACC=1 EXOSCALE_API_KEY=... EXOSCALE_API_SECRET=... \
    go test ./pkg/resources/iam/ -run "TestIAM/ResourceRole" -v -timeout 10m
=== RUN   TestIAM
=== PAUSE TestIAM
=== CONT  TestIAM
=== RUN   TestIAM/ResourceRole
=== PAUSE TestIAM/ResourceRole
=== CONT  TestIAM/ResourceRole
--- PASS: TestIAM (0.00s)
    --- PASS: TestIAM/ResourceRole (14.22s)
PASS
ok      github.com/exoscale/terraform-provider-exoscale/pkg/resources/iam      14.238s
```

### Unit Tests
```
$ go test ./pkg/resources/iam/ -run TestResourceRoleSchema -v
=== RUN   TestResourceRoleSchema
=== PAUSE TestResourceRoleSchema
=== CONT  TestResourceRoleSchema
--- PASS: TestResourceRoleSchema (0.00s)
PASS
ok      github.com/exoscale/terraform-provider-exoscale/pkg/resources/iam      0.021s
```

> [!NOTE]
> PR description and boilerplate code, both AI assisted with GitHub Copilot.

### CODE REVIEW

**Comment by natalie-o-perret** [comment]
[SC-176221]

File: pkg/resources/iam/resource_role_test.go [hunk 1]
```diff
@@ -2,16 +2,66 @@ package iam_test
...
+	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
 	"github.com/hashicorp/terraform-plugin-testing/helper/acctest"
-	"github.com/hashicorp/terraform-plugin-testing/helper/resource"
+	tfresource "github.com/hashicorp/terraform-plugin-testing/helper/resource"
 	"github.com/hashicorp/terraform-plugin-testing/terraform"
 )
 
+// TestResourceRoleSchema checks schema-level properties of exoscale_iam_role
+// without requiring API credentials (no TF_ACC needed).
+func TestResourceRoleSchema(t *testing.T) {
```
Comment (kobajagi) [inline pkg/resources/iam/resource_role_test.go]: I think this type of test is a waste of CPU cycles. Schema changes are reviewed and any change is a conscious decision by developer. There is little to no benefit of testing schema did not change.

**Review by kobajagi — APPROVED** [review]

File: pkg/resources/iam/resource_role_test.go (hunk 1 above)
Comment (kobajagi) [reply pkg/resources/iam/resource_role_test.go]: Not a hard requirement to remove, but advisable.

Comment (natalie-o-perret) [reply pkg/resources/iam/resource_role_test.go]: ~~Imo, similar type of rationale as my reply in #521 (but weaker), wdyt? https://github.com/exoscale/terraform-provider-exoscale/pull/521#discussion_r3147924202~~

~~I'm mainly worried about a new service type being added without the validator wired up, wdyt?~~

~~(Not holding a strong opinion on it tho, genuinely asking, do you have a rule of thumb for this?)~~

In hindsight, fair, just asserting a decision wasn't undone, so not much value, will remove that one.
